version: "1"
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-3000}
    environment:
      NODE_ENV: PRODUCTION
    env_file:
      - ./.env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
